inputSet:
  name: Build_Generate_my_Pipeline_configuration_1682578360036-push-trigger-input-set
  identifier: Build_Generate_my_Pipeline_configuration_1682578360036pushtriggerinputset
  orgIdentifier: default
  projectIdentifier: test
  pipeline:
    identifier: Build_Generate_my_Pipeline_configuration_1682578360036
    properties:
      ci:
        codebase:
          build:
            type: branch
            spec:
              branch: <+trigger.branch>
