name: Sample Pipeline_1682571781610
stages:
  - name: build
    spec:
      steps:
        - name: go_build
          spec:
            run: go build
          type: script
        - name: go_test
          spec:
            run: go test -v ./...
          type: script
    type: ci
version: 1
